<?php

namespace App\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCount(){
        $query = $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->getQuery();
        $result = $query->getSingleScalarResult();
        return $result;
    }
}
