<?php

namespace App\Repository;
use App\Entity\Poll;
use App\Entity\User;

/**
 * PollAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollAnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnswerByPollAndUser(Poll $poll, User $user){
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.poll', 'p')
            ->where('p = :poll')
            ->andWhere('a.user = :user')
            ->setParameter('poll', $poll)
            ->setParameter('user', $user)
            ->getQuery();
        return $query->getResult();
    }

    public function getAnswerByPoll(Poll $poll){
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.poll', 'p')
            ->where('p = :poll')
            ->setParameter('poll', $poll)
            ->getQuery();
        return $query->getResult();
    }
}
