<?php

namespace App\Repository;
use App\Entity\Poll;
use App\Entity\User;

/**
 * PollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCount(){
        $query = $this->createQueryBuilder('p')
            ->select('count(p.id)')
            ->getQuery();
        $result = $query->getSingleScalarResult();
        return $result;
    }
}
