<?php

namespace App\Repository;

use App\Entity\UploadedVideo;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * ProviderVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderVideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCount(){
        $query = $this->createQueryBuilder('pv')
            ->select('count(pv.id)')
            ->getQuery();
        $result = $query->getSingleScalarResult();
        return $result;
    }
}
