<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCount(){
        $query = $this->createQueryBuilder('u')
            ->select('count(u.id)')
            ->getQuery();
        $result = $query->getSingleScalarResult();
        return $result;
    }
}
