# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: root
    mailer_password: root
    youtube_api_key: '%env(YOUTUBE_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Twig\PollExtension:
        tags:
          - { name: twig.extension }
        arguments: [ '@doctrine.orm.entity_manager' ]

    App\Twig\VideosExtension:
        tags:
          - { name: twig.extension }
        arguments: [ '@doctrine.orm.entity_manager' ]

    App\Twig\ArticlesExtension:
           tags:
             - { name: twig.extension }
           arguments: [ '@doctrine.orm.entity_manager' ]

    App\Twig\MessageExtension:
           tags:
             - { name: twig.extension }
           arguments: [ '@doctrine.orm.entity_manager' ]

    App\Twig\UserExtension:
           tags:
             - { name: twig.extension }
           arguments: [ '@doctrine.orm.entity_manager' ]

    App\Twig\CoreExtension:
           tags:
             - { name: twig.extension }
           arguments: [ '@doctrine.orm.entity_manager' ]

    App\Twig\BackofficeExtension:
           tags:
             - { name: twig.extension }
           arguments: [ '@doctrine.orm.entity_manager' ]

    App\Utils\YoutubeHelper:
        arguments: ['%youtube_api_key%']
        public: true
