global:
    site_name: 'Videa CMS'
    description: 'Platform for video sharing and more...'
    version: 0.0.1
    theme: default
    social: { facebook: 'http://dddd.com', twitter: null, youtube: null }
